services:
  db:
    image: postgres:17.7-alpine
    container_name: libraryManagementSystem-db
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d:ro

  app:
    build:
      context: ./app
    image: library-management-system:latest
    container_name: libraryManagementSystem-app
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - db
    command: npm start

volumes:
  db-data:
