services:
  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  app:
    build:
      context: ./app
    container_name: node-app
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          ignore:
            - node_modules/
            - test/
            - "*.log"
        - action: rebuild
          path: ./app/package.json
        - action: rebuild
          path: ./app/package-lock.json

volumes:
  db-data:
