services:
  db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - ci_net

  app:
    build:
      context: ./app
    container_name: node-app
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    depends_on:
      - db
    command: npm start
    networks:
      - ci_net

volumes:
  db-data:

networks:
  ci_net:
    driver: bridge
