name: SIMPLE-CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Install deps
        run: npm ci

      - name: Security audit (fail high/critical)
        run: npm audit --audit-level=high || (echo "Vulnerabilità >=high trovate" && exit 1)

      - name: Lint
        run: npm run lint

  build-scan-test:
    runs-on: ubuntu-latest
    needs: lint-audit
    steps:
      - uses: actions/checkout@v4

      - name: Copy .env from example
        run: cp .env.example .env

      - name: Compose build 
        run: docker compose up -d --build 
    
      - name: Trivy scan app image (HIGH,CRITICAL)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: node:alpine
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Trivy scan postgres:15-alpine (HIGH,CRITICAL)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'postgres:15-alpine'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Run integration tests
        run: docker compose exec -T app npm run test

      - name: Cleanup
        if: always()
        run: docker compose down -v
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-scan-test
    steps:
      - name: Deploy (simulato)
        run: echo "Simulazione deploy può avvenire su servizio cloud(AWS) o in locale."

