name: SIMPLE-CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json
      - name: Install deps
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Security audit (fail high/critical)
        run: |
          set -e
          npm audit --audit-level=high || (echo "Vulnerabilità >=high trovate" && exit 1)

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint-and-audit
    steps:
      - uses: actions/checkout@v4

      - name: Copy .env from example
        run: cp .env.example .env

      - name: Compose up (build + start)
        run: docker compose up -d --build

      - name: Run integration tests 
        run: sleep 5 && docker compose exec -T app npm run test

      - name: Logs (on failure)
        if: failure()
        run: |
          docker compose ps
          docker compose logs db || true
          docker compose logs app || true

      - name: Cleanup
        if: always()
        run: docker compose down -v
